apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.omegagpt.sandbox.appName }}
  labels:
    app: {{ .Values.omegagpt.sandbox.appName }} {{ include "itijsin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.omegagpt.sandbox.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.omegagpt.sandbox.appName }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.omegagpt.sandbox.appName }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - env:
            - name: NPM_CONFIG_REGISTRY
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: npm.config.registry
          image: "{{ .Values.image.repository | trimSuffix "/" }}/{{ .Values.omegagpt.sandbox.imageName }}:{{ .Values.omegagpt.sandbox.tag }}"
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          name: {{ .Values.omegagpt.sandbox.imageName }}
          ports:
            - containerPort: {{ .Values.omegagpt.sandbox.port }}
              name: http
              protocol: TCP
            - containerPort: {{ .Values.omegagpt.codePlugin.port }}
              name: code-plugin
              protocol: TCP
          resources: {{- toYaml .Values.resources | nindent 12 }}
